//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR.LST.ConferenceXP {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PresentationCapability.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Black Pen 的本地化字符串。
        /// </summary>
        internal static string BlackPen {
            get {
                return ResourceManager.GetString("BlackPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blue Highlighter 的本地化字符串。
        /// </summary>
        internal static string BlueHighlighter {
            get {
                return ResourceManager.GetString("BlueHighlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blue Pen 的本地化字符串。
        /// </summary>
        internal static string BluePen {
            get {
                return ResourceManager.GetString("BluePen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Close 的本地化字符串。
        /// </summary>
        internal static string CloseHotkey {
            get {
                return ResourceManager.GetString("CloseHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConferenceXP Presentation 的本地化字符串。
        /// </summary>
        internal static string ConferencexpPresentation {
            get {
                return ResourceManager.GetString("ConferencexpPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Overwrite 的本地化字符串。
        /// </summary>
        internal static string ConfirmImageOverwriteCaption {
            get {
                return ResourceManager.GetString("ConfirmImageOverwriteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operation may overwrite existing images.  Are you sure you want to proceed? 的本地化字符串。
        /// </summary>
        internal static string ConfirmImageOverwriteMessage {
            get {
                return ResourceManager.GetString("ConfirmImageOverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Erase All 的本地化字符串。
        /// </summary>
        internal static string EraseAll {
            get {
                return ResourceManager.GetString("EraseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eraser 的本地化字符串。
        /// </summary>
        internal static string Eraser {
            get {
                return ResourceManager.GetString("Eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error during communication: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorDuringCommunication {
            get {
                return ResourceManager.GetString("ErrorDuringCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error in opening {0}, error message: {1} 的本地化字符串。
        /// </summary>
        internal static string ErrorInOpening {
            get {
                return ResourceManager.GetString("ErrorInOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error in opening {0}
        ///Type not supported 的本地化字符串。
        /// </summary>
        internal static string ErrorInOpeningFileType {
            get {
                return ResourceManager.GetString("ErrorInOpeningFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error in opening {0}
        ///Version may be out of date 的本地化字符串。
        /// </summary>
        internal static string ErrorInOpeningVersion {
            get {
                return ResourceManager.GetString("ErrorInOpeningVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occured during navigation, the page might be absent or might be still in the download process 的本地化字符串。
        /// </summary>
        internal static string ErrorOccuredDuringNavigation {
            get {
                return ResourceManager.GetString("ErrorOccuredDuringNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while taking snapshot.  Your target snapshot window may be in an invalid state or closed. 的本地化字符串。
        /// </summary>
        internal static string ErrorWhileTakingSnapshot {
            get {
                return ResourceManager.GetString("ErrorWhileTakingSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;File 的本地化字符串。
        /// </summary>
        internal static string FileHotkey {
            get {
                return ResourceManager.GetString("FileHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For more information, see http://cct.cs.washington.edu/downloads/CXP/
        ///
        ///Presentation : {0}
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string ForMoreInformationSee {
            get {
                return ResourceManager.GetString("ForMoreInformationSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Highlighter 的本地化字符串。
        /// </summary>
        internal static string Highlighter {
            get {
                return ResourceManager.GetString("Highlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Importing Doc Document 的本地化字符串。
        /// </summary>
        internal static string ImportingDocDocument {
            get {
                return ResourceManager.GetString("ImportingDocDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Importing Excel Document 的本地化字符串。
        /// </summary>
        internal static string ImportingExcelDocument {
            get {
                return ResourceManager.GetString("ImportingExcelDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Importing PowerPoint document... 的本地化字符串。
        /// </summary>
        internal static string ImportingPowerpointDocument {
            get {
                return ResourceManager.GetString("ImportingPowerpointDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index must be within the collection. 的本地化字符串。
        /// </summary>
        internal static string IndexMustBeWithinTheCollection {
            get {
                return ResourceManager.GetString("IndexMustBeWithinTheCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Blank Slide 的本地化字符串。
        /// </summary>
        internal static string InsertBlankSlide {
            get {
                return ResourceManager.GetString("InsertBlankSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Screen Shot 的本地化字符串。
        /// </summary>
        internal static string InsertScreenShot {
            get {
                return ResourceManager.GetString("InsertScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lime Highlighter 的本地化字符串。
        /// </summary>
        internal static string LimeHighlighter {
            get {
                return ResourceManager.GetString("LimeHighlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Slide 的本地化字符串。
        /// </summary>
        internal static string NextSlide {
            get {
                return ResourceManager.GetString("NextSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Next Slide 的本地化字符串。
        /// </summary>
        internal static string NextSlideHotkey {
            get {
                return ResourceManager.GetString("NextSlideHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Open 的本地化字符串。
        /// </summary>
        internal static string OpenHotkey {
            get {
                return ResourceManager.GetString("OpenHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Remote... 的本地化字符串。
        /// </summary>
        internal static string OpenRemote {
            get {
                return ResourceManager.GetString("OpenRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page Not Found! 的本地化字符串。
        /// </summary>
        internal static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pen 的本地化字符串。
        /// </summary>
        internal static string Pen {
            get {
                return ResourceManager.GetString("Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PresentationCapabilityFMain 的本地化字符串。
        /// </summary>
        internal static string PresentationCapabilityFMain {
            get {
                return ResourceManager.GetString("PresentationCapabilityFMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Presentation Help 的本地化字符串。
        /// </summary>
        internal static string PresentationHelp {
            get {
                return ResourceManager.GetString("PresentationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Slide 的本地化字符串。
        /// </summary>
        internal static string PreviousSlide {
            get {
                return ResourceManager.GetString("PreviousSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Previous Slide 的本地化字符串。
        /// </summary>
        internal static string PreviousSlideHotkey {
            get {
                return ResourceManager.GetString("PreviousSlideHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receiving Page:  {0} / {1} 的本地化字符串。
        /// </summary>
        internal static string ReceivingPage {
            get {
                return ResourceManager.GetString("ReceivingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receiving Page: 1 / {0} 的本地化字符串。
        /// </summary>
        internal static string ReceivingPage_of_ {
            get {
                return ResourceManager.GetString("ReceivingPage_of_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Red Pen 的本地化字符串。
        /// </summary>
        internal static string RedPen {
            get {
                return ResourceManager.GetString("RedPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resend Current Slide 的本地化字符串。
        /// </summary>
        internal static string ResendCurrentSlide {
            get {
                return ResourceManager.GetString("ResendCurrentSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resending current slide... 的本地化字符串。
        /// </summary>
        internal static string ResendingCurrentSlide {
            get {
                return ResourceManager.GetString("ResendingCurrentSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resending slides... 的本地化字符串。
        /// </summary>
        internal static string ResendingSlides {
            get {
                return ResourceManager.GetString("ResendingSlides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rtDocument == null 的本地化字符串。
        /// </summary>
        internal static string RtDocumentIsNull {
            get {
                return ResourceManager.GetString("RtDocumentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen Shot Information 的本地化字符串。
        /// </summary>
        internal static string ScreenShotInformation {
            get {
                return ResourceManager.GetString("ScreenShotInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Application 的本地化字符串。
        /// </summary>
        internal static string SelectApplication {
            get {
                return ResourceManager.GetString("SelectApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Screen Shot 的本地化字符串。
        /// </summary>
        internal static string SelectScreenShot {
            get {
                return ResourceManager.GetString("SelectScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sending slides... 的本地化字符串。
        /// </summary>
        internal static string SendingSlides {
            get {
                return ResourceManager.GetString("SendingSlides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slide  {0} of {1} 的本地化字符串。
        /// </summary>
        internal static string Slide_Of_ {
            get {
                return ResourceManager.GetString("Slide_Of_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slide  -- of -- 的本地化字符串。
        /// </summary>
        internal static string Slide_Of_Placeholder {
            get {
                return ResourceManager.GetString("Slide_Of_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Slide 的本地化字符串。
        /// </summary>
        internal static string SlideHotkey {
            get {
                return ResourceManager.GetString("SlideHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slide Show 的本地化字符串。
        /// </summary>
        internal static string SlideShow {
            get {
                return ResourceManager.GetString("SlideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snapshot of {0} 的本地化字符串。
        /// </summary>
        internal static string SnapshotOf {
            get {
                return ResourceManager.GetString("SnapshotOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snapshots of minimized windows cannot be taken.{0}Please restore or maximize the window. 的本地化字符串。
        /// </summary>
        internal static string SnapshotsOfMinimizedWindows {
            get {
                return ResourceManager.GetString("SnapshotsOfMinimizedWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Tools 的本地化字符串。
        /// </summary>
        internal static string ToolsHotkey {
            get {
                return ResourceManager.GetString("ToolsHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conference leader tried to navigate to a page you have not recieved.  Try using the &quot;Resend All Slides&quot; button to resolve this issue. 的本地化字符串。
        /// </summary>
        internal static string TryResendAllSlidesButton {
            get {
                return ResourceManager.GetString("TryResendAllSlidesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to find Page for current TOCNode 的本地化字符串。
        /// </summary>
        internal static string UnableToFindPage {
            get {
                return ResourceManager.GetString("UnableToFindPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected highlighter color &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string UnexpectedHighlighterColor {
            get {
                return ResourceManager.GetString("UnexpectedHighlighterColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected pen color &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string UnexpectedPenColor {
            get {
                return ResourceManager.GetString("UnexpectedPenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 value greater than MaxPageNum 的本地化字符串。
        /// </summary>
        internal static string ValueGreaterThanMaxpagenum {
            get {
                return ResourceManager.GetString("ValueGreaterThanMaxpagenum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whiteboard {0} 的本地化字符串。
        /// </summary>
        internal static string Whiteboard {
            get {
                return ResourceManager.GetString("Whiteboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whiteboard 1 的本地化字符串。
        /// </summary>
        internal static string Whiteboard1 {
            get {
                return ResourceManager.GetString("Whiteboard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whiteboard Session 的本地化字符串。
        /// </summary>
        internal static string WhiteboardSession {
            get {
                return ResourceManager.GetString("WhiteboardSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yellow Highlighter 的本地化字符串。
        /// </summary>
        internal static string YellowHighlighter {
            get {
                return ResourceManager.GetString("YellowHighlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yellow Pen 的本地化字符串。
        /// </summary>
        internal static string YellowPen {
            get {
                return ResourceManager.GetString("YellowPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must first open a document. 的本地化字符串。
        /// </summary>
        internal static string YouMustFirstOpenADocument {
            get {
                return ResourceManager.GetString("YouMustFirstOpenADocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must first select a screen shot by clicking Select Screen Shot on the Slide menu, and then clicking the screen shot you want. 的本地化字符串。
        /// </summary>
        internal static string YouMustFirstSelectAScreenShot {
            get {
                return ResourceManager.GetString("YouMustFirstSelectAScreenShot", resourceCulture);
            }
        }
    }
}
